### ISSUE TITLE
Please consider making a new release

### ISSUE THREAD

**Issue by mavit** [cute-jumper/parsec.el#11]
The latest released version, 0.1.3, dates from 2016.  Please consider tagging a newer version so that the latest fixes show up in, e.g., MELPA Stable.

Thanks.

**Comment by cute-jumper** [comment]
Done

**Comment by appetrosyan** [comment]
Hi! 

Can this issue be properly fixed? 

It's closed, but none of the upstream versions of parsec (all three main branches), and none of the packages on ELPA point to the version that was stated [here](https://github.com/wbolster/emacs-gvariant/issues/4), 

`0.1.4`

I think the best way is probably to actually upload the newly tagged version.
